import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

// Color tokens, font families, radii and spacing ported 1:1 from the original
// admin_ui.html inline `tailwind.config` so the visual design is preserved.
const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#8d9385',
        // --- aligned 1:1 with user_ui.html palette ---
        'on-secondary': '#003732',
        'on-surface-variant': '#8e989e',
        'on-surface': '#ffffff',
        'on-tertiary-fixed': '#2c1600',
        'inverse-primary': '#456730',
        'tertiary-container': '#fdb66e',
        'tertiary-fixed': '#ffdcbe',
        'primary-fixed': '#c5efa9',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#693c00',
        'on-primary-container': '#bceb9c',
        'secondary-container': '#005049',
        'surface-container-low': '#111415',
        'secondary-fixed': '#76f7e7',
        'surface-container-lowest': '#0d0f10',
        error: '#f28b82',
        'on-error': '#410002',
        'on-tertiary-container': '#774503',
        'surface-dim': '#0d0f10',
        secondary: '#5ce0d0',
        'on-secondary-fixed-variant': '#005049',
        'inverse-on-surface': '#2f3132',
        'surface-container-high': '#1c2021',
        'primary-container': '#a8d08d',
        'on-primary-fixed': '#092100',
        surface: '#141819',
        'surface-tint': '#aad28f',
        'surface-container-highest': '#272b2c',
        'secondary-fixed-dim': '#56dbcb',
        'on-tertiary': '#4a2800',
        'inverse-surface': '#e2e2e3',
        'on-secondary-container': '#003832',
        'surface-container': '#171b1c',
        'on-primary': '#112b00',
        background: '#0d0f10',
        'error-container': '#a50010',
        primary: '#a8d08d',
        'tertiary-fixed-dim': '#ffb870',
        'surface-variant': '#1c2021',
        tertiary: '#ffb870',
        warning: '#fdd663',
        'on-secondary-fixed': '#00201d',
        'on-primary-fixed-variant': '#2e4f1a',
        'primary-fixed-dim': '#aad28f',
        'surface-bright': '#222627',
        'outline-variant': '#43493e',
        'on-background': '#ffffff',
        'muted-custom': 'rgba(142, 152, 158, 0.6)',
        'brand-accent': '#5ce0d0',
      },
      borderRadius: {
        DEFAULT: '0.1rem',
        lg: '0.39rem',
        xl: '0.585rem',
        full: '0.78rem',
      },
      spacing: {
        'container-margin': '24px',
        'card-stat-p': '20px',
        'gap-md': '16px',
        'gap-xs': '4px',
        'card-row-p': '16px',
        'gap-sm': '8px',
      },
      fontFamily: {
        'label-sm': ['Geist'],
        'body-md': ['Geist'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        display: ['Hanken Grotesk'],
        'body-lg': ['Geist'],
        badge: ['Geist'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        display: ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        badge: ['10px', { lineHeight: '12px', letterSpacing: '0.03em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
