import type { SkillProfile, SkillVersion } from '@/types';
import { SkillWorkspace } from './SkillWorkspace';

/** Splits "142ms p50 • 380ms p99" → ["142ms", "p50 • 380ms p99"]. */
function splitFirstWord(s: string): [string, string] {
  const i = s.indexOf(' ');
  return i === -1 ? [s, ''] : [s.slice(0, i), s.slice(i + 1)];
}

/** Splits "98.7% (NeMo + garak)" → ["98.7%", "(NeMo + garak)"]. */
function splitParen(s: string): [string, string] {
  const i = s.indexOf('(');
  return i === -1 ? [s.trim(), ''] : [s.slice(0, i).trim(), s.slice(i).trim()];
}

function MetadataRow({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex justify-between items-center">
      <span className="text-on-surface-variant font-body-md text-body-md">{label}</span>
      {children}
    </div>
  );
}

function PerformanceBar({ version }: { version: SkillVersion }) {
  const production = version.status === 'production';
  return (
    <div className="flex items-center gap-3">
      <div
        className={`flex-1 h-1.5 w-24 rounded-full overflow-hidden relative ${
          production ? 'bg-gradient-to-r from-[#5ce0d0]/20 to-[#333536]' : 'bg-[#141617]'
        }`}
      >
        <div
          className={`h-full ${production ? 'bg-[#5ce0d0]' : 'bg-[#83898d]'}`}
          style={{ width: `${version.performance}%` }}
        />
      </div>
      <span className={`font-bold font-mono ${production ? 'text-[#5ce0d0]' : 'text-on-surface-variant'}`}>
        {version.performance.toFixed(1)}%
      </span>
    </div>
  );
}

export function OverviewPanel({ profile }: { profile: SkillProfile }) {
  const { metadata, versions } = profile;
  const [latencyMain, latencyRest] = splitFirstWord(metadata.latency);
  const [safetyMain, safetyRest] = splitParen(metadata.safetyScore);
  const [clusterMain, clusterRest] = splitParen(metadata.originCluster);
  const summaryRows = versions.slice(0, 3);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-gap-md">
      <div className="lg:col-span-2 space-y-6">
        <SkillWorkspace profile={profile} />
      </div>

      <div className="glass-card rounded-lg p-card-stat-p h-fit">
        <span className="font-badge text-badge uppercase text-on-surface-variant block mb-6">
          SKILL METADATA
        </span>
        <div className="space-y-5">
          <div className="flex justify-between items-start">
            <span className="text-on-surface-variant font-body-md text-body-md">Trigger Pattern</span>
            <span className="font-mono text-on-surface font-medium text-body-md text-right">
              {metadata.triggerPattern}
            </span>
          </div>
          <MetadataRow label="Origin Cluster">
            <span className="text-error font-medium text-body-md">
              {clusterMain} {clusterRest && <span className="text-[10px] ml-1">{clusterRest}</span>}
            </span>
          </MetadataRow>
          <MetadataRow label="Generated By">
            <span className="text-on-surface font-medium text-body-md">{metadata.generatedBy}</span>
          </MetadataRow>
          <MetadataRow label="Safety Score">
            <span className="text-secondary font-bold text-body-md">
              {safetyMain}{' '}
              {safetyRest && (
                <span className="font-label-sm text-[10px] ml-1 text-on-surface-variant">{safetyRest}</span>
              )}
            </span>
          </MetadataRow>
          <MetadataRow label="Temporal Workflow">
            <a className="text-secondary hover:underline font-medium text-body-md" href="#">
              {metadata.temporalWorkflow}
            </a>
          </MetadataRow>
          <MetadataRow label="Avg Latency">
            <span className="text-on-surface font-medium text-body-md">
              {latencyMain}{' '}
              {latencyRest && (
                <span className="text-on-surface-variant font-label-sm text-[10px] ml-2">{latencyRest}</span>
              )}
            </span>
          </MetadataRow>
        </div>
      </div>

      <div className="lg:col-span-3 glass-card rounded-lg overflow-hidden">
        <div className="p-card-stat-p flex items-center justify-between border-b border-white/5">
          <span className="font-badge text-badge uppercase text-on-surface-variant">
            VERSION HISTORY — {versions.length} VERSIONS · {versions.length - 1} ANCESTORS
          </span>
          <button className="text-secondary font-label-sm text-label-sm hover:underline">
            Download CSV
          </button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-white/5 bg-[#0d0f10] text-[10px] font-bold text-on-surface-variant uppercase tracking-wider">
                <th className="p-card-row-p">VERSION</th>
                <th className="p-card-row-p">STATUS</th>
                <th className="p-card-row-p">CREATED</th>
                <th className="p-card-row-p">METHOD</th>
                <th className="p-card-row-p">PERFORMANCE</th>
                <th className="p-card-row-p">ANCESTOR</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 font-body-md text-body-md text-on-surface">
              {summaryRows.map((v) => (
                <tr key={v.version} className="hover:bg-white/[0.02] transition-colors group cursor-pointer">
                  <td className="p-card-row-p font-bold font-mono">{v.version}</td>
                  <td className="p-card-row-p">
                    {v.status === 'production' ? (
                      <span className="bg-[#1a2324] text-[#5ce0d0] px-2 py-0.5 rounded font-badge text-[10px] font-bold uppercase border border-[#5ce0d0]/20">
                        Production
                      </span>
                    ) : (
                      <span className="bg-[#222425] text-on-surface-variant px-2 py-0.5 rounded font-badge text-[10px] font-bold uppercase border border-white/5">
                        Archived
                      </span>
                    )}
                  </td>
                  <td className="p-card-row-p text-on-surface-variant">{v.created}</td>
                  <td className="p-card-row-p text-on-surface-variant">{v.releaseType}</td>
                  <td className="p-card-row-p">
                    <PerformanceBar version={v} />
                  </td>
                  <td className="p-card-row-p text-on-surface-variant font-mono">{v.ancestor}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
